### ISSUE TITLE
The game saving is missing.

### ISSUE THREAD

**Issue by INFCode** [ailec0623/DQN_HollowKnight#3]
It is said that there is a saving for those who do not play HollowKnight in the README file but it seems that there are actually no such file (`/save_file/user3.dat`) in this repository. Is it missing or moved to another place? Thanks for any help.

**Comment by ailec0623** [comment]
Sorry, I haven't checked GitHub recently.
I committed the save file to another branch.
Now I have added the archive file in the main branch
